------liquibase formatted sql
------
------ changeset elebedeva:1
CREATE TABLE ADS
(
    ID INTEGER generated by default as identity primary key,
    PRICE INTEGER,
    TITLE VARCHAR
--    USER_ID   INTEGER references user (id) on delete set null
) ;
