------liquibase formatted sql
------
------changeset kkorzhuk:1
CREATE TABLE comment
(
    ID           INTEGER generated by default as identity primary key,
    CREATED_AT TIMESTAMP,
    TEXT        VARCHAR


);
--ALTER TABLE comment
--ADD ADS_ID INTEGER references ads (ID) on delete set null;
--ALTER TABLE comment
--ADD USER_ID INTEGER references user (id) on delete set null;