------liquibase formatted sql
------
------changeset kkorzhuk:1
CREATE TABLE IF NOT EXISTS comment
(
    ID           INTEGER generated by default as identity primary key,
    CREATED_AT TIMESTAMP,
    TEXT        VARCHAR
    ,
    ADS_ID INTEGER references ADS (id) on delete set null,
    USER_ID INTEGER references users (id) on delete set null

);
