------liquibase formatted sql
------
------changeset kkorzhuk:1
CREATE TABLE IMAGE
(
    ID                INTEGER generated by default as identity primary key,
    FILE_PATH VARCHAR not null,
    FILE_EXTENSION VARCHAR not null,
    TEXT        VARCHAR not null,
    FILE_SIZE BIGINT not null,
    MEDIA_TYPE VARCHAR not null
--    ADS_ID references ads (id) on delete set null,
--    USER_ID BIGINT references user (id) on delete set null
);