------liquibase formatted sql
------
------changeset aglinka:1
CREATE TABLE user
(
    ID          INTEGER generated by default as identity primary key,
    EMAIL       VARCHAR unique not null,
    FIRST_NAME  VARCHAR not null,
    LAST_NAME   VARCHAR not null,
    PHONE       VARCHAR not null,
    ROLE        VARCHAR not null,
    PASSWORD    VARCHAR not null,
    REG_DATE    DATE not null,
    AVATAR_ID   VARCHAR references image (id) on delete set null
);
